version: '3.7'

services:

  restapi-powerflows:
    container_name: ${api_container_name}
    hostname: ${api_hostname}
    build:
      context: ${api_context}
      dockerfile: ${api_dockerfile}
    restart: always
    env_file:
      - ${api_env_file}
    ports:
      - ${api_ports1}
    networks:
      - ${global_services_network}
#    depends_on:
#      - "minio-powerflows"
#      - "postgres-powerflows"
    command: ${api_command1}


 
networks:
  powerflows-network:
    driver: bridge