---
  appconstants:
  - connection_groups:
    - cos
    - db
    - localfs
  - connection_types:
    - pg
    - minio
    - ibmcos
    - localfiles
  - data_formats:
    - txt
    - csv
    - json
    - yaml 
    - parquet
    - orc
    - arrow
  - table_formats:
    - iceberg
    - delta
  - storage_type:
    - source_system
    - job_storage
  - operation_parameter_types:
    - url
    - fspath
    - cospath
    - cosbuket
  - default_csv_separator: ","
  - sqlite_db_file: /tmp/result_files/secrets.db #todo use in secrets manager
  - default_pg_secret_name: PostGreSQL Default #todo use in secrets manager
  - default_minio_secret_name: Minio Default #todo use in secrets manager
  - job_config_format: yaml #todo use in rest job route
