---
jobconfig:
  name: unit testing localfs capabilities
  grouping_id: dbjobs
  connections:
  - Minio Default
  - localfs
  - PostGreSQL Default
  operations:
  - capability: 
      from_connection: localfs
      name: writeRestUrlToFile
      order: 1
      stepname: download from url to localfilesystem
      config:
      - parameter:
        name: source_url
        value: http://www.google.com
      - parameter: 
        name: target_path
        value: /tmp/result_files/test_ping_google.txt
  - capability: 
      from_connection: localfs
      order: 2
      name : UploadToCOS
      stepname: download from cos test
      config:
      - parameter:
        name: cos_connection
        value: Minio Default
      - parameter: 
        name: cos_bucket
        value : transfers
      - parameter: 
        name: cos_object_fullname
        value: powerflows_test.text
      - parameter: 
        name: source_filepath
        value: /tmp/result_files/test_ping_google.txt
  - capability: 
      from_connection: PostGreSQL Default
      order: 3
      name : executeQuery
      stepname: Test for query execution
      config:
      - parameter:
        name: sql_query
        value: SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
      - parameter: 
        name: with_results
        value : true
