---
jobconfig:
  name: unit testing localfs capabilities
  grouping_id: dbjobs
  connections:
  - Minio Default
  - localfs
  - PostGreSQL Default
  operations:
  - capability:
      from_connection: localfs
      name: writeRestUrlToFile
      order: 1
      stepname: download from url to localfilesystem
      config:
      - parameter:
        name: source_url
        value: http://www.google.com
      - parameter:
        name: target_path
        value: "/tmp/result_files/test_ping_google.txt"
  - capability:
      from_connection: localfs
      order: 2
      name: UploadToCOS
      stepname: download from cos test
      config:
      - parameter:
        name: cos_connection
        value: Minio Default
      - parameter:
        name: cos_bucket
        value: transfers
      - parameter:
        name: cos_object_fullname
        value: powerflows_test.text
      - parameter:
        name: source_filepath
        value: "/tmp/result_files/test_ping_google.txt"
  - capability:
      from_connection: PostGreSQL Default
      order: 3
      name: executeQuery
      stepname: Test for query execution
      config:
      - parameter:
        name: sql_query
        value: SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
      - parameter:
        name: with_results
        value: true
  - capability:
      from_connection: HTTP for HitBTC
      order: 4
      name: performHttpRequest
      stepname: Perform HitBTC Symbols Fetch
      config:
      - parameter:
        name: requests_list
        value:
        - url: https://api.hitbtc.com/api/3/public/currency
          operation: GET
          parameters: {}
          data: {}
          headers: {}
          result_mime_type: application/json
          result_expected_params:
            todo1: definerealstructure to map to result
          result_save_name: BTCUSDT_hitbtc_symbols
        - url: https://api.hitbtc.com/api/3/public/ticker
          operation: GET
          use_saved_data: BTCUSDT_hitbtc_symbols
          use_saved_for: parameters
          use_saved_variable_name: symbols
          parameters:
            symbols: BTCUSDT
          data: {}
          headers: {}
          result_mime_type: application/json
          result_expected_params:
            todo1: definerealstructure to map to result
        - url: https://api.hitbtc.com/api/3/public/ticker
          operation: GET
          use_saved_data: BTCETH_hitbtc_symbols
          use_saved_for: parameters
          use_saved_variable_name: symbols
          parameters:
            symbols: ETHBTC
          data: {}
          headers: {}
          result_mime_type: application/json
          result_expected_params:
            todo1: definerealstructure to map to result
  - capability:
      from_connection: PostGreSQL Default
      order: 5
      name: uploadFileToTableFromLocalfs
      stepname: Test for query execution
      config:
      - parameter:
        name: localfs_connection
        value:
      - parameter:
        name: infer_structure
        value:
      - parameter:
        name: target_schema
        value:
      - parameter:
        name: target_table
        value: